// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const expoConfig = require('eslint-config-expo/flat');

module.exports = defineConfig([
  expoConfig,
  {
    // `dist/*` is the production web build; `.expo/*` is Expo's own generated cache
    // (including `.expo/types/router.d.ts`, regenerated by the dev server on every route
    // change - this task adds two new routes under `app/settings/calendars/`, which is what
    // surfaced this). Both are gitignored build artifacts, never hand-edited, so neither
    // belongs under this project's own lint rules any more than `node_modules` does.
    ignores: ['dist/*', '.expo/*'],
  },
]);
